<head>
  <meta name="author" content="Rogério de Oliveira">
  <meta institution="author" content="Universidade Presbiteriana Mackenzie">
</head>

<img src="http://meusite.mackenzie.br/rogerio/mackenzie_logo/UPM.2_horizontal_vermelho.jpg" width=300, align="right">
<!-- <h1 align=left><font size = 6, style="color:rgb(200,0,0)"> optional title </font></h1> -->

---

https://github.com/rafaelgildin/IA_2023S2

# Exercícios

## Exercício: **CASE Tips**

Acesse a base de dados http://meusite.mackenzie.br/rogerio/data_load/tips.csv para as questões a seguir.

In [ ]:
import pandas as pd
df = pd.read_csv('http://meusite.mackenzie.br/rogerio/data_load/tips.csv')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

## Q0. Considere nossa base exemplo Tips. Considerando somente os finais de semana, quem tem média de participantes na mesa maior, fumantes ou não fumantes?

In [ ]:
df.day.value_counts()

Sat     87
Sun     76
Thur    62
Fri     19
Name: day, dtype: int64

In [ ]:
df[df.day.isin(['Sat','Sun'])].smoker.value_counts()

No     102
Yes     61
Name: smoker, dtype: int64

In [ ]:
df[df.day.isin(['Sat','Sun'])].groupby('smoker').mean()

<ipython-input-142-a2f5da224df5>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df[df.day.isin(['Sat','Sun'])].groupby('smoker').mean()

        total_bill       tip      size
smoker
No       20.133922  3.139216  2.764706
Yes      22.162295  3.075246  2.508197

## Exercício: **CASE Insurance**

Acesse a base de dados http://meusite.mackenzie.br/rogerio/data_load/insurance.csv para as questões a seguir.

In [ ]:
df = pd.read_csv('http://meusite.mackenzie.br/rogerio/data_load/insurance.csv')
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

## Q1. Qual percentual de homens e mulheres assegurados na base?

In [ ]:
df.sex.value_counts(normalize=True).round(2)

male      0.51
female    0.49
Name: sex, dtype: float64

## Q2. Qual o total dos valor de seguros pago por homens e mulheres segurados na base?

In [ ]:
df_agg_sex = df.groupby('sex').sum()
df_agg_sex

<ipython-input-17-28f7808ee77e>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_agg_sex = df.groupby('sex').sum()

          age        bmi  children       charges
sex
female  26151  20110.070       711  8.321061e+06
male    26308  20917.555       754  9.434764e+06

## Q3. Qual o precentual de valor de seguros pagos por homens e mulheres segurados na base?

In [ ]:
total_charges = df_agg_sex.charges.sum()
(df_agg_sex.charges/total_charges).round(2)

sex
female    0.47
male      0.53
Name: charges, dtype: float64

## Q4. Não fumantes apresentam em média mais filhos?

In [ ]:
df.groupby('smoker').mean()

<ipython-input-28-cd9be18b1d80>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('smoker').mean()

              age        bmi  children       charges
smoker
no      39.385338  30.651795  1.090226   8434.268298
yes     38.514599  30.708449  1.113139  32050.231832

## Q5. Qual a média e maior de idade dentre os segurados homem, das regiões northwest ou northeast?

In [ ]:
df[(df.sex == 'male') & (df.region.isin(['northwest','northeast']))]\
  ['age'].describe().round(1)

count    324.0
mean      38.8
std       14.1
min       18.0
25%       26.0
50%       39.0
75%       51.0
max       64.0
Name: age, dtype: float64



## Exercício: **CASE:** **European Energy:**

Qual o tipo de Energia mais produzido na Europa? O uso de fontes renováveis já é significativo?

[European Energy link](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-08-04/readme.md)

Explore aqui como é a produção de Energia na Europa empregando a base de dados abaixo. Você pode achar útil fazer uma exploração inicial dos dados antes de começar.

In [ ]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-04/energy_types.csv')
df.head()

,country,country_name,type,level,2016,2017,2018
0,BE,Belgium,Conventional thermal,Level 1,30728.0,31316.0,30092.635
1,BE,Belgium,Nuclear,Level 1,41430.0,40128.5,26995.628
2,BE,Belgium,Hydro,Level 1,1476.0,1360.9,1239.248
3,BE,Belgium,Pumped hydro power,Level 2,1110.0,1093.2,983.190
4,BE,Belgium,Wind,Level 1,5340.0,6387.9,7177.346

## Q6. Quantos tipos de energia e países diferentes há na base?

In [ ]:
df.nunique()

country          37
country_name     36
type              8
level             2
2016            194
2017            203
2018            184
dtype: int64

## Q7. Qual o percentual de energia nuclear produzido na Europa no ano de 2018?

In [ ]:
df.type.value_counts()

Conventional thermal    37
Nuclear                 37
Hydro                   37
Pumped hydro power      37
Wind                    37
Solar                   37
Geothermal              37
Other                   37
Name: type, dtype: int64

In [ ]:
df_agg_type = df.groupby('type')['2018'].agg(['sum'])
total_sum = df_agg_type['sum'].sum()
(df_agg_type['sum']/total_sum).round(2)

type
Conventional thermal    0.45
Geothermal              0.00
Hydro                   0.16
Nuclear                 0.23
Other                   0.00
Pumped hydro power      0.01
Solar                   0.03
Wind                    0.11
Name: sum, dtype: float64

## Q8. Qual o percentual de energia nuclear produzido na França no ano de 2018?

In [ ]:
df2 = df[(df['country_name'] == 'France')].copy()
df_agg_type = df2.groupby('type')['2018'].agg(['sum'])
total_sum = df_agg_type['sum'].sum()
(df_agg_type['sum']/total_sum).round(2)

type
Conventional thermal    0.10
Geothermal              0.00
Hydro                   0.12
Nuclear                 0.70
Other                   0.00
Pumped hydro power      0.02
Solar                   0.02
Wind                    0.05
Name: sum, dtype: float64

## Q9. Qual o percentual de energias limpas produzida na Europa no ano de 2018?

*Energias limpas somente Hidroelétrica, Eólica, Solar e Geotérmica.*

In [ ]:
clean_energys = ['Hydro','Pumped hydro power','Wind','Solar','Geothermal']
df.loc[:,'clean_type'] = False
df.loc[(df['type'].isin(clean_energys)),'clean_type'] = True

# create agg
df_agg_type = df.groupby(['clean_type'])['2018'].agg(['sum'])
total_sum = df_agg_type['sum'].sum()
(df_agg_type['sum']/total_sum)

clean_type
False    0.681363
True     0.318637
Name: sum, dtype: float64

## Q10. Considerando os anos de 2016, 2017 e 2018, a produção de energias limpas tem aumentado na Europa? Verifique em termos absolutos e percentuais.

*Energias limpas somente Hidroelétrica, Eólica, Solar e Geotérmica.*

In [ ]:
df_agg = df.groupby('clean_type')[['2016','2017','2018']].sum()

# calculate percentage
for col in df_agg.columns:
  col_sum = df_agg[col].sum()
  df_agg.loc[:,f"{col}_p"] = (df_agg[col]/col_sum).round(2)

df_agg

                   2016         2017         2018  2016_p  2017_p  2018_p
clean_type
False       2678682.167  2710684.793  2580782.547    0.71    0.71    0.68
True        1105192.814  1110958.759  1206892.083    0.29    0.29    0.32